apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  port: "8080"
  user-management-addr: "user-management-service:50051"
  payment-service-url: "http://payment-service:3001"
  order-service-url: "http://order-service:3002"
  user-management-service-url: "http://user-management-service:3003"
  chat-service-url: "http://chat-service:3004"
