apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  USER_MANAGEMENT_ADDR: "user-management-service:50051"
  PAYMENT_SERVICE_URL: "http://payment-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3002"
  USER_MANAGEMENT_SERVICE_URL: "http://user-management-service:3003"
  CHAT_SERVICE_URL: "http://chat-service:3004"