apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  rest-port: "3002"
  docker-env: "true"
  db-host: "host.docker.internal"
  db-port: "5432"
  db-name: "orderdb"
  db-sslmode: "disable"
  course-service-addr: "course-service:50052"
