apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: horo/course-service
          ports:
            - containerPort: 3005 # REST API port (http)
              name: http
            - containerPort: 50052 # gRPC port
              name: grpc
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: REST_PORT
              value: "3005"
            - name: GRPC_PORT
              value: "50052"
            - name: USER_MANAGEMENT_SERVICE_ADDR
              value: "user-management-service:50051"

            # Database configuration
            - name: DB_NAME
              value: "coursedb"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - port: 3005
      name: http
      targetPort: 3005
    - port: 50052
      name: grpc
      targetPort: 50052
  type: ClusterIP
