apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: horo/chat-service
          ports:
            - containerPort: 3004
              name: http
            - containerPort: 50053 # gRPC port
              name: grpc
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            # Service configuration
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: http-port
            # Secrets
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: uri
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: grpc-port
            - name: USER_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: chat-service-config
                  key: user-service-addr
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - port: 3004
      name: http
      targetPort: 3004
    - port: 50053
      name: grpc
      targetPort: 50053
  type: ClusterIP
